### ISSUE TITLE
"badluck" should return "Bad luck Brian"

### ISSUE THREAD

**Issue by captbaritone** [captbaritone/urlmeme#6]
Instead it returns a bear.

**Comment by seanlane** [comment]
Looks like `badluck` matches evenly with `bad luck bear` and `bad luck brian`, which seems algorithmically correct. Maybe have it randomly select even results instead of having it pick the first one?

**Comment by captbaritone** [comment]
Hmm, that makes sense. I think it's best for the results to be deterministic. I suppose it's just up to the user to scope down their request by adding either "bear" or "brian" Thanks for digging into this for me!
